### ISSUE TITLE
FEEDBACKS:: stagetimer: Message showing

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-stagetimerio-api#10]
Unable to select an MESSAGE ID or MESSAGE INDEX. Feedback get state of the first message only. So it is not known which message is shown.

**Comment by lhermann** [comment]
Question: Are you using it with the web version or the offline version?

**Comment by Suenee** [comment]
> Question: Are you using it with the web version or the offline version?

All reports I made for you are from web version. :-)

**Comment by lhermann** [comment]
After some consideration I decided not to provide feedback about the specific messages and their content. As opposed to timers, where one timer is always highlights regardless if it is running or now, there's no "highlighted" message. So the currently available actions and presets are sufficient.
