### ISSUE TITLE
Unable to reset current timer

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-stagetimerio-api#11]
The reset button requires entering the timer index. How should I reset the current timer if I don't know its index? In the previous version of the API, it was possible to reset the current timer (without index). I'm missing this feature in API v1.

**Comment by lhermann** [comment]
The `Transport: Previous` action does exactly this: Resetting the current timer without providing an id/index.

```
stagetimer: Transport: Previous
 
Reset the highlighted timer in the room if it is running. If the highlighted timer is not running, highlight the previous timer in the list. Optionally, you can automatically start the previous timer once it's highlighted.
```

**Comment by Suenee** [comment]
Hi Lukas!

Yes it is true. That's what I figured out, but it's impractical. I will describe the scenario that happened to me because of this:

WHEN IT WORKS RIGHT:
* I have three time slots
* The first has already taken place and is taking the second.
* Time is stopped.
* I give the PREVIOUS button. Time will go back to the beginning.
* Second slot timer starts...

WHEN IT DOESN'T WORK LOGICALLY:
* I have three time slots
* The 2nd time slot to start is selected
* Time has not yet run.
* I have a button in COMPANION that should do a sequence of actions:
1. return the time slot to the beginning (the PREVIOUS action) in case the time was started prematurely or there was a wrong TAKE.
2. start recording/broadcasting
3. start the timer of the current slot

ERROR: In this case the PREVIOUS action moves the index to the 1st time slot because the 2nd time slot has not yet run.

In API v0.x this worked correctly. It was possible to send a RESET command without knowing the timer index. The value of the currently running/standing/selected timer was used as the index.

PS: Thank you for the great job.

**Comment by lhermann** [comment]
Good point. Thanks for the detailed explanation. Will add a reset action to the list 👍 .

**Comment by Suenee** [comment]
> Good point. Thanks for the detailed explanation. Will add a reset action to the list 👍 .

In which Companion version will this be published please?

**Comment by lhermann** [comment]
Lot's of other things have been taking my attention, that's why I haven't come around to this issue yet.

**Comment by lhermann** [comment]
The new API enpoint `/reset` and companion module action `Transport: Reset` fix this problem. It resets the current timer (optionally autostarts it) without ever moving to the previous timer.
