### ISSUE TITLE
COUNT UP - missing variable of current time

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-stagetimerio-api#12]
If the timer is counting down from zero (COUNT UP), the variable that shows the current time is missing. In the variables, there is only information about the deduction from the upper limit of the timer.

**Comment by lhermann** [comment]
Thanks @Suenee, I'll put this on the list for our next bugfixing round 👍

**Comment by lhermann** [comment]
The new `$(stagetimer:timeDisplay)` variable and `Time Display` preset show the time equal to the Stagetimer output, taking timer appearance (countdown, count up, time of day) into account.
