### ISSUE TITLE
Missing command: stagetimer: Timer: Reset

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-stagetimerio-api#14]
I am looking for a command to reset the time period according to the Index or TimerId. The same function could solve #11. If I do not enter a number, the current segment will be reset.

**Comment by lhermann** [comment]
I looked into it. Instead of making the index optional, I'll add a "Transport: Reset" action that just resets the current time with an `autostart` option.

**Comment by Suenee** [comment]
Good idea, thank you

**Comment by lhermann** [comment]
The new API enpoint `/reset` and companion module action `Transport: Reset` fix this problem. It resets the current timer (optionally autostarts it) without ever moving to the previous timer.
