### ISSUE TITLE
Using websocket to get variables

### ISSUE THREAD

**Issue by lhermann** [bitfocus/companion-module-stagetimerio-api#2]
The current web socket API is not documented and uses Firebase authentication tokens.

In order to have variables available in Companion we need add a publicly available and documented web socket that uses the same authentication method `Authorization: Bearer YOUR_API_KEY`

Events (thinking out loud):
- Timer changes (start, stop, reset, ...)
- Message changes (show, hide, color, text, ...)
- Blackout (true, false)

What time/date format works best for Companion? Will ISO strings work? `"2021-12-03T06:52:14.141Z"`

In response to:

> @estilles @nacalai creator of stagetimer.io here. Sorry for reviving this thread 😅
>
> Currently the API does not return values. Internally we use web sockets. How could we make values like message text or current time available as variables in Companion?

Hey Lukas! We spoke briefly via email a few weeks ago. I've been meaning to send you and Liz a message regarding adding feedbacks and variables to the module.

There're many ways to tackle this, but since you're already using web sockets internally, that might be the way to go. I guess my questions are:

- Do you have the web sockets API documented?
- Does is use any sort of authentication (like Room ID and API Key)?

If the answers to these questions are yes, then we can definitely use web sockets to add feedbacks and variables to the module.

This is a separate topic though. We should probably create a separate issue.

_Originally posted by @estilles in https://github.com/bitfocus/companion-module-hermann-stagetimerio/issues/1#issuecomment-985256752_

**Comment by estilles** [comment]
> In order to have variables available in Companion we need add a publicly available and documented web socket that uses the same authentication method `Authorization: Bearer YOUR_API_KEY`

That would be great! I'm assuming the module will stop using the REST API, and this new web sockets API will will provide the ability to both trigger Stagetimer actions and receive state/feedbacks as well. Correct?

Is this new web sockets API currently on your roadmap?

> Events (thinking out loud):
> - Timer changes (start, stop, reset, ...)
> - Message changes (show, hide, color, text, ...)
> - Blackout (true, false)

Definitely. I can probably think of a few more.

**Comment by lhermann** [comment]
> This new web sockets API will provide the ability to both trigger Stagetimer actions and receive state/feedbacks as well. Correct?

Should not be too difficult to implement all endpoints as events. So yes.

> Is this new web sockets API currently on your roadmap?

It is now ;)

> Definitely. I can probably think of a few more.

By all means, please :)

**Comment by estilles** [comment]
That's great news. Please let me know when you have an API I can use to test and update this module.

Right now your REST API provides the ability to:

- start/stop/toggle/reset/flash the current timer in a room
- select the next/previous timer in a room
- "tweak" add/substract time from the current timer in a room
- toggle blackout on/off the timer in a room
- ping a room
- start/stop/toggle/reset/flash a specific timer
- set a specific timer as the current timer
- show/hide/toggle/flash a message in a room

The following could be useful:

### Settings
- Hide Logo
- Hide progress bar
- Logo size
- Logo position: top left/top center/top right/center left/center/center right/bottom left/bottom/center/bottom right
- Set timer font/size
- Set message font/size
- Set text to default/high contrast/inverted/shadow
- Set text to default/white/black/green screen/blue screen/corporate/parchment/crowd/pencils/stars/streets

### Timers
- Set timer title/extra
- Set timer trigger mode: manual/linked/schedule/until
- Set timer Duration
- Set timer wake-up time (yellow/red)
- Show/hide/toggle title

### Messages
- Set message text
- set message color white/green/read
- Set/toggle text attributes: bold/case

---

It would be nice to have to ability to retrieve the state of the following:

- For Feedbacks and variables
  - logo show/hide state
  - progress bar show/hide state
  - room blackout state
  - timer start/stop state
  - message show/hide state

- Additional variables
  - Timer title/extra
  - Timer time remaining
  - Message text

--- 

I'm sure I'm missing something. If I remember I'll update this thread.

**Comment by lhermann** [comment]
@estilles I'll get back to you as soon as I have time to work in this. Probably early January 👍

**Comment by estilles** [comment]
Sounds good @lhermann. I'll be standing by.

**Comment by MatteoGheza** [comment]
> Sounds good @lhermann. I'll be standing by.

Can I help you working on this?

**Comment by lhermann** [comment]
Hey @estilles, sorry for the delay here. I had some personal things coming in between. The topic is till top 2 on our priority list.

**Comment by estilles** [comment]
@lhermann! Great to hear from you. I was out sick for a while as well at the beginning of the year. I'm back now, so will just stand by for your updates.

**Comment by davidjoshuaford** [comment]
Following this project with interest!

+1 to get countdown timer variables back into Companion so a countdown clock and feedback colors can be added to a button.

**Comment by lhermann** [comment]
@davidjoshuaford I did not forget about this. stagetimer.io became a bit more propular than I expected so I'm knee-deep into scaling right now which unfortunately took priority.

**Comment by davidjoshuaford** [comment]
Great to hear of its success! We used it on a live broadcast over the weekend and it kept our east coast and west coast studios in sync. 

Would love to see ST feedback coming into Companion so that buttons can be triggered by a ST producer. 

ie when a Stage Timer producer starts a timer, it presses a button to switch AUX outputs, play hyperdeck, mutes a mic etc. You could essentially build program cues around it and automate a ROS.

**Comment by estilles** [comment]
@lhermann I'm more than happy to continue helping out whenever you're ready.

**Comment by lhermann** [comment]
New API is released including a publicly available websocket: https://stagetimer.io/docs/api-v1/

**Comment by MatteoGheza** [comment]
@estilles let me know if I can help you
