### ISSUE TITLE
Upgrading the module for API V1 (release scheduled for May 1, 2023)

### ISSUE THREAD

**Issue by lhermann** [bitfocus/companion-module-stagetimerio-api#6]
stagetimer.io's V1 of the API is scheduled to release on May 1, 2023 with the following features:
- more endpoints (create/update/delete timers and messages)
- return values for all endpoints
- socket.io endpoint for push events
- support for OSC protocoll in addition to HTTP (maybe)

Once it is released I'll post the full spec here.

**Comment by nacalai** [comment]
Awesome! Can't wait
